# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lucygui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LucyGUI(object):
    def setupUi(self, LucyGUI):
        LucyGUI.setObjectName("LucyGUI")
        LucyGUI.resize(1351, 820)
        self.centralwidget = QtWidgets.QWidget(LucyGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1351, 821))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/arghy/Downloads/Main.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 20, 301, 71))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(1030, 20, 301, 71))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border:none")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, -30, 411, 211))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/arghy/Downloads/sideline.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1140, 610, 211, 211))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/arghy/Downloads/World.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        LucyGUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(LucyGUI)
        QtCore.QMetaObject.connectSlotsByName(LucyGUI)

    def retranslateUi(self, LucyGUI):
        _translate = QtCore.QCoreApplication.translate
        LucyGUI.setWindowTitle(_translate("LucyGUI", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LucyGUI = QtWidgets.QMainWindow()
    ui = Ui_LucyGUI()
    ui.setupUi(LucyGUI)
    LucyGUI.show()
    sys.exit(app.exec_())
